services:
  sophia-ai-service:
    build:
      context: .
    container_name: sophia-ai-service
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/home/app
    networks:
      - net1

networks:
  net1:
    external: true
    name: net1
